name: Demo Workflow 2

on:
  repository_dispatch:
    types: [trigger-workflow-2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
           username: ${{  secrets.DOCKER_USERNAME  }}
           password: ${{  secrets.DOCKER_PASSWORD  }}
      - name: Build Docker image
        run: |
          docker build -t my-docker-image .
          docker run -d my-docker-image
      - name: List images
        run: |
         docker image ls
       
      - name: Push Docker image to Docker Hub
        run: docker push my-docker-image:latest
