name: Demo Workflow 1

on:
  workflow_dispatch:
   inputs:
      text_content:
        description: 'Text content for Text.txt'
        required: true
  repository_dispatch:
        types: [trigger-workflow-1]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if Text.txt exists
        run: |
         if [ -f "Text.txt" ]; then
          echo "${{ github.event.inputs.text_content }}" > Text.txt
          git config --global user.name "Indhu1024"
          git config --global user.email "indhuchandran10@gmail.com"
          git add Text.txt
          git commit -m "Add content to Text.txt"
          git push
         else
          echo "Text.txt already exists"
          exit 0
         fi
       #  echo "Text.txt exists"
        # exit 0
       # else
        #  echo "Text.txt does not exist"
       # echo "Hello, World!" > Text.txt
            
            
        

      - name: Trigger Workflow 2
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          repository: Indhu1024/Workflow
          event-type: trigger-workflow-2
