name: Scheduled Workflow
on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker pull indhu1024/workflow:newtag

      - name: Run Docker container
        run: docker run indhu1024/workflow:newtag cat /path/to/mytextfile.txt
