on:
  push:
    branches:
      - GWS_214
name: Json file into table format
jobs:
  table:
    runs-on: ubuntu-latest
    name: Update README from json data
    steps:
      
        - name: Checkout repository
          uses: actions/checkout@v2
  
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11.5
  
        - name: Run Python Script
          run: python generate_table.py
