name: Publish Sarif into github pages
on: 
  push:
    branches: 
      - GWS_214
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload sarif artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-html-report
          path: output.html
  download-and-deploy:
    runs-on: ubuntu-latest
    needs: upload-artifact
    permissions:
      contents: read
      pages: write
      id-token: write
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}  
    steps: 
      - name: Download output.html
        uses: crazy-max/ghaction-github-pages@v4
        with:
          name: sarif-html-report
          path: ./sarif-report
      - name: Configure pages
        uses: actions/configure-pages@v1 
      - name: upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: sarif-html-report
          path: ./sarif-report
      - name: Deploy code
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: sarif-html-report
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          