name: Publish Sarif into github pages
on: 
  push:
    branches: 
      - gh-pages
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload sarif artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-html-report
          path: index.html
  download-and-deploy:
    runs-on: ubuntu-latest
    needs: upload-artifact
    permissions:
      contents: read
      pages: write
      id-token: write
    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}  
    steps: 
      - name: Create directory
        run: |
          mkdir -p sarif-report
      - name: Download index.html
        uses: actions/download-artifact@v2
        with:
          name: sarif-html-report
          path: ./sarif-report
      - name: Configure pages
        uses: actions/configure-pages@v1 
      # - name: upload pages artifact
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     name: sarif-html-pages
      #     path: ./sarif-report
      - name: test
        run: |
           ls
      - name: Deploy code
        id: deployment
        uses: crazy-max/ghaction-github-pages@v4 
        with:
          artifact_name: sarif-html-report
          publish_dir: ./sarif-report
          #target_branch: GWS_214
          build_dir: ./sarif-report
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          