name: Publish Sarif into github pages
on: 
  push:
    branches: 
      - GWS_214
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Upload sarif artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-html-report
          path: output.html
  download-and-deploy:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps: 
      - name: Download output.html
        uses: actions/download-artifact@v2
        with:
          name: sarif-html-report
      - name: Deploy code
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          publish_dir: ./sarif-html-report
