name: SARIF Visualization Workflow
on:
  push:
   paths:
      - 'converted_report.md'
jobs:
  validate-sarif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display SARIF Report
        run: cat converted_report.md
    
