name: Docker Build and SARIF Conversion

on:
  push:
    branches:
      - GWS_214

jobs:
  build-and-convert-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Docker container
        run: |
          docker run -v $(pwd):/sarif sarif_docker_container \
          ./sarif convert  --o output.html cx.sarif
          docker cp $(docker ps -q -n=1):/sarif/output.html ./output.html
    
      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-html-output
          path: ./output.html
