name: SARIF Visualization Workflow
on:
   workflow_dispatch:
jobs:
  validate-sarif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install security-scanner 
        run: npm install -g security-scanner 

      - name: Generate SARIF report
        run: security-scanner  --output-file report.sarif 
        
      - name: Upload SARIF report
        uses: actions/upload-artifact@v2
        with:
          name: sarif-report
          path: report.sarif

      - name: Generate SARIF Visualization
        uses: khulnasoft-labs/tfsecurity-sarif-action@v1
        with:
          input-file: cx.sarif
          output-file: cx.html
