name: Docker Build and SARIF Conversion

on:
  push:
    branches:
      - GWS_214

jobs:
  build-and-convert-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: docker image pull indhu1024/workflow:newtag
    
      - name: Run Docker container
        run: docker run indhu1024/workflow:newtag 
    
      - name: Run SARIF Conversion Container
        run: |
          docker run -v "$(pwd):/sarif" Indhu1024/sarif_docker_container:latest /bin/bash -c "sarif convert -t html -o /sarif/output.html /sarif/cx.sarif"
          
      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-html-output
          path: ./output.html
