name: Docker Build and SARIF Conversion

on:
  push:
    branches:
      - main

jobs:
  build-and-convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t your-dockerhub-username/sarif-converter:latest .
        working-directory: ./path-to-your-Dockerfile-directory

      - name: Push Docker Image to Docker Hub
        run: |
          docker push your-dockerhub-username/sarif-converter:latest
        working-directory: ./path-to-your-Dockerfile-directory

      - name: Run SARIF Conversion Container
        run: |
          docker run -v "$(pwd):/sarif" your-dockerhub-username/sarif-converter:latest /bin/bash -c "sarif convert -t html -o /sarif/output.html /sarif/cx.sarif"
        working-directory: ./path-to-sarif-file-directory

      - name: Copy Output HTML to Artifact Directory
        run: |
          cp output.html ${{ github.workspace }}/output.html
        working-directory: ./path-to-sarif-file-directory

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-html-output
          path: ${{ github.workspace }}/output.html
