name: SARIF Visualization Workflow
on:
   workflow_dispatch:
      
jobs:
  validate-sarif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert SARIF to Markdown
        run: |
         python convert_sarif_to_md.py cx.sarif > converted_report.md
         echo "::set-output name=markdown::$(cat converted_report.md)"
      - name: Upload Markdown Report
        uses: actions/upload-artifact@v2
        with:
         name: converted-report
         path: converted_report.md

      - name: Comment with Markdown Report
        uses: actions/github-script@v4
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}
         script: |
          const fs = require('fs');
          const markdownContent = fs.readFileSync('converted_report.md', 'utf8');
          github.issues.createComment({
            issue_number: context.payload.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: markdownContent,
          });
