name: SARIF Validation Workflow
on: 
   pull_request:
    types:
      - opened
      - synchronize

jobs:
  sarif-multitool:
    name: SARIF Multitool
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        dotnet tool install --global Sarif.Multitool --version 4.3.1
        export PATH="$PATH:/root/.dotnet/tools"

    - name: Convert SARIF to HTML
      run: |
        sarif-multitool convert cx.sarif --output output.json
        jq -c '.runs[].results[] | { ruleId, message, level: .level | .level, locations: .locations[].physicalLocation | { file: .artifactLocation.uri, line: .region.startLine, column: .region.startColumn } }' output.json > report.json
        # Generate basic HTML report directly in the workflow
        echo '<html><head><title>SARIF Report</title></head><body>' > output.html
        jq -r '.[] | "<p><strong>Rule ID:</strong> \(."ruleId")<br><strong>Message:</strong> \(."message")<br><strong>Level:</strong> \(."level")<br><strong>File:</strong> \(."locations".file)<br><strong>Line:</strong> \(."locations".line)<br><strong>Column:</strong> \(."locations".column)</p>"' report.json >> output.html
        echo '</body></html>' >> output.html

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: sarif-html-report
        path: output.html






     
