name: SARIF Validation Workflow
on: 
   pull_request:

jobs:
  validate-sarif:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SARIF Multitool
      uses: microsoft/sarif-actions@v0.1
      with:
        # Command to be sent to SARIF Multitool
        command: 'validate cx.sarif'
    - name: Convert SARIF to Markdown
      id: sarif-to-md
      run: |
        python sarif_to_markdown.py cx.sarif
      continue-on-error: true

    - name: Print Markdown Report
      run: |
        echo "${{ steps.sarif-to-markdown.outputs.markdown }}"








   
