name: SARIF Validation Workflow
on: 
   workflow_dispatch:

jobs:
  validate-sarif:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: SARIF Multitool
      uses: microsoft/sarif-actions@v0.1
      with:
        # Command to be sent to SARIF Multitool
        command: 'validate C:\Users\ibalacha\Downloads\cx.sarif'
