name: Workflow 1

on:
  workflow_dispatch:

jobs:
  add_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create file
        run: |
          echo "Hello World" > Sample text.txt
          
   - name: Read file content
        run: |
          file_path="Sample text.txt"
          if [ -f "$file_path" ]; then
            cat "$file_path"
          else
            echo "File not found: $file_path"
            exit 1
          fi 

     
