name: Workflow 1

on:
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

     
      - name: Write to file
        run: |
          file_path="Sample.txt"
          echo "This content will overwrite the file." | tee -a "$file_path"
     
    # - name: Commit and push changes
     #   uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
       #   commit_message: "Update file content via GitHub Actions" 
