name: Workflow 1

on:
  workflow_dispatch:

jobs:
  add_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create file
        run: |
          echo "Hello World" > Sample text.txt
          

- name: Write to file
        run: |
          file_path="Sample text.txt"
          echo "This content will overwrite the file." | tee -a "$file_path"
     
