name: Workflow 1

on:
  workflow_dispatch:

jobs:
  add_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create file
        run: |
          echo "Hello World" > Sample text.txt
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add content to sample text.txt"
          commit_user_name: "Indhu1024"
          commit_user_email: "indhuchandran10@gmail.com"


     
